/**
 * List all Action types used in the application
 */
export default {

  SET_USER: 'SET_USER',
  SET_ORDER: 'SET_ORDER',
  SET_LIST_ORDERS: 'SET_LIST_ORDERS',
  SET_LIST_PLACES: 'SET_LIST_PLACES',
  SET_LIST_ASSIGNMENTS: 'SET_LIST_ASSIGNMENTS',
  SET_PLACE_OF_ASSIGNMENT: 'SET_PLACE_OF_ASSIGNMENT',
  SET_ASSIGNMENT: 'SET_ASSIGNMENT',
  SET_LIST_OFFERS: 'SET_LIST_OFFERS',
  SET_OFFER: 'SET_OFFER',
  SET_LIST_APPLIES: 'SET_LIST_APPLIES',
  SET_ORDER_APPLIES: 'SET_ORDER_APPLIES',
}