/**
 * List all Action types used in the application
 */
export default {

  SET_USER: 'SET_USER',
  SET_ORDER: 'SET_ORDER',
  SET_LIST_ORDERS: 'SET_LIST_ORDERS',
  SET_LIST_STACKPOWER: 'SET_LIST_STACKPOWER',
  SET_LIST_OFFERS: 'SET_LIST_OFFERS',
  SET_OFFER: 'SET_OFFER',
  SET_LIST_APPLIES: 'SET_LIST_APPLIES',
  SET_ORDER_APPLIES: 'SET_ORDER_APPLIES',
  SET_SCATTER: 'SET_SCATTER'
}